### ISSUE TITLE
Use with WebRTC

### ISSUE THREAD

**Issue by The-Code-Monkey** [bloatless/php-websocket#12]
I want to be able to make this server connect the client to the server via a webrtc stream how would i do this??

is this even possible?

i need to be able to encode the stream from the client directly to the server in some way FFmpeg??

**Comment by nekudo** [comment]
I believe that is not possible. WebRTC is a different protocol - it can not connect to a WebSocket Server.

**Comment by The-Code-Monkey** [comment]
You use websockets to connect the web rtc check this java implementation antmedia.io obviously we don't have a java tech stack so its not something we can develop with easily but if we had a php one we could.
