### ISSUE TITLE
StatusApplication may loose clients

### ISSUE THREAD

**Issue by DanRoche** [bloatless/php-websocket#20]
the serverClients array store client connections by port,   thus  if another client ( with different IP )  is connecting with the same port as a previous one -> the first client is lost !

this patch solve the problem : 
-------------------- src/Application/StatusApplication.php --------------------
index 6469453..7400d94 100644
@@ -97,7 +97,7 @@ class StatusApplication extends Application
      */
     public function clientConnected(string $ip, int $port): void
     {
-        $this->serverClients[$port] = $ip;
+        $this->serverClients[$ip.":".$port] = date("U");
         $this->serverClientCount++;
         $this->statusMsg('Client connected: ' . $ip . ':' . $port);
         $data = [
@@ -118,10 +118,10 @@ class StatusApplication extends Application
      */
     public function clientDisconnected(string $ip, int $port): void
     {
-        if (!isset($this->serverClients[$port])) {
+        if (!isset($this->serverClients[$ip.":".$port])) {
             return;
         }
-        unset($this->serverClients[$port]);
+        unset($this->serverClients[$ip.":".$port]);
         $this->serverClientCount--;
         $this->statusMsg('Client disconnected: ' . $ip . ':' . $port);
         $data = [

**Comment by DanRoche** [comment]
i can see that  the patch syntax does not format correctly !

so here again  :
in function clientConnected()
replace 
$this->serverClients[$port] = $ip;
by 
$this->serverClients[$ip.":".$port] = date("U");

and symetrically in function clientDisconnected()
replace 
unset($this->serverClients[$port]);
by 
unset($this->serverClients[$ip.":".$port]);

**Comment by nekudo** [comment]
Hello Dan. 

I'm not entirely sure if it is even possible that the Socket-Handling of the OS assigns the same port to multiple IPs in this case. Nevertheless I added a fix to a branch for a new version. Please check if this solves your problem.

**Comment by DanRoche** [comment]
Hello Nekudo, 

i had the case 2 or 3 times this past week,  ( i was running programs with lot of connection to the websocket server ! )
i confirm that it is possible to have the same socket destination port with different IP !
thank you for the fix.

**Comment by nekudo** [comment]
Fixed in v2.1.0
