### ISSUE TITLE
Adding a Client.php Message Listener

### ISSUE THREAD

**Issue by JavanXD** [bloatless/php-websocket#23]
In your [client example](https://github.com/bloatless/php-websocket/blob/master/cli/client_demo.php) you provided a example on how to send a message with `$client->sendData`. I've checked the Client.php but could not find a way to listen for a new Message from the Server.php. Do you support bi-directional communication? You already have [a function](https://github.com/bloatless/php-websocket/blob/bed1714f1aeb24efa03915dff28c71276a68d6c4/src/Connection.php#L294) to send a message from server to the client.

**Comment by nekudo** [comment]
The Client.php was removed in the latest version of this project.

**Comment by JavanXD** [comment]
That's not the response I've expected @nekudo 
Do you support bi-directional communication?

**Comment by nekudo** [comment]
Hello,

in case you really need a websocket client with listening capabilities, there are other projects focusing on that, like e.g.: https://github.com/ratchetphp/Pawl

But, it is unlikely that you actually need a PHP based Client. Here is why:

- In case you need to communicate with the clients connected to your server from the machine the server is running on, you should put that logic into the application. See: https://github.com/bloatless/php-websocket#applications
- In case you need to push data into the running server you should use the push-client: https://github.com/bloatless/php-websocket#push-client-ipc
- In case you want to communicate with the websocket-server from another machine: You _could_ use a websocket client for this, but it is not recommended as you most probably run into security/permission problems.

Hope this helps.
