### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by fabMoth4n** [bloatless/php-websocket#26]
In Server.php line 212 
'maxRequetsPerMinute' => $this->maxRequestsPerMinute,

left side Requets without 's' befor 't'

**Comment by nekudo** [comment]
Thanks for the Hint. This code will be removed in the next version 3.0.0 (https://github.com/bloatless/php-websocket/commit/58afa2c875fa718ac206f10722d4940369889580#diff-3eea692e203ad76df7232885d33c0dc396c9c4c807c5ce1ded7b03663c04882bL212)
