### ISSUE TITLE
socket_bind creates file in /tmp, but www-data has no permissions to it

### ISSUE THREAD

**Issue by fearr1** [bloatless/php-websocket#28]
Server.php -> openIPCSocket() -> socket_bind -> creates a file in /tmp but www-data has no permissions to use it. This happened when i tried to send IPC data from an action of a website to the WebSocket server. This change did the trick:

FROM
if (socket_bind($this->icpSocket, $ipcSocketPath) === false) {
    throw new \RuntimeException('Could not bind to ipc socket.');
}

TO
if (socket_bind($this->icpSocket, $ipcSocketPath) === false) {
    throw new \RuntimeException('Could not bind to ipc socket.');
} else {
    chown($ipcSocketPath, 'www-data');
}

**Comment by nekudo** [comment]
I added a fix for this. It is now possible to set user/group and mode for the IPC file:

```php
$server = new \Bloatless\WebSocket\Server('127.0.0.1', 8000, '/tmp/phpwss.sock');
$server->setIPCOwner('foo');
$server->setIPCGroup('www-data');
$server->setIPCMode(0755);
```

Keep in mind that the user you start the server with needs to be in the desired group for this to work.
