### ISSUE TITLE
 Class "Bloatless\WebSocket\Examples\Application\Chat" not found

### ISSUE THREAD

**Issue by MasumNishat** [bloatless/php-websocket#34]
Hello,

Maybe this is a `composer.json` problem,
`Chat.php` is available in respective location, but my application could not recognize that.
On the other hand, `Bloatless\WebSocket\Application\StatusApplication` is found and working fine.

    Error

    Class "Bloatless\WebSocket\Examples\Application\Chat" not found
    
    at F:\Server\app\Console\Commands\webSocket.php:53
     49▕         $server->setMaxConnectionsPerIp(20);
     50▕
     51▕ // add your applications
     52▕         $server->registerApplication('status', StatusApplication::getInstance());
     ➜  53▕         $server->registerApplication('chat', Chat::getInstance());
     54▕
     55▕ // start the server
     56▕         $server->run();

Tnanks in advance.

**Comment by nekudo** [comment]
I can't reproduce this error.
