### ISSUE TITLE
how to do private message using php-websocket Bloatless V2.0 ?

### ISSUE THREAD

**Issue by HardiYana-creator** [bloatless/php-websocket#39]
I'm using php websocket Bloatless V2.0, because my framework (Zend) only supports php 7.2. I've been able to send messages through the web socket, but messages can be received by all connected clients (Broadcast). How can you do private messages between the server and only one client, so that messages sent by the server are not received by other connected clients?

**Comment by nekudo** [comment]
The Status-Application includes an example for this: https://github.com/bloatless/php-websocket/blob/release/2.1.0/src/Application/StatusApplication.php#L49

Just use the $client->send() Method to send data to a specific client.

**Comment by HardiYana-creator** [comment]
can it also be implemented in DemoApplication? and how is the implementation? I've tried the DemoAplication for private chat but it didn't work. maybe I was wrong in implementing it.
