### ISSUE TITLE
Release v3.0.2

### ISSUE THREAD

**Issue by mario-deluna** [bloatless/php-websocket#44]
The commit https://github.com/bloatless/php-websocket/commit/cc7d6d8a2ac7635efd9c3fb5e5f5fa0828e5f151 fixes a fatal error in which I ran as-well.  

As it is the only change on master since `v3.0.1` could we get a quick hotfix release? 

Best Regards
Mario

**Comment by mateusan** [comment]
+1

**Comment by nekudo** [comment]
I merged some PRs and created a new release. Thx to all contributers.
